"""initial schema

Revision ID: 0f853a4a6ae1
Revises: 
Create Date: 2026-08-28 19:06:23.955238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

revision: str = '0f853a4a6ae1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required extensions - must exist before any geometry/vector columns.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('typical_min_investment', sa.Float(), nullable=True),
    sa.Column('typical_max_investment', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('dataset_name', sa.String(length=200), nullable=True),
    sa.Column('collection_date', sa.DateTime(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('geographic_coverage', sa.String(length=200), nullable=True),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=True),
    sa.Column('reliability', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_updates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('performed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('geographic_scope', sa.String(length=200), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_assumption_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('default_beneficiary_contribution_pct', sa.Float(), nullable=False),
    sa.Column('default_loan_pct', sa.Float(), nullable=False),
    sa.Column('min_project_cost', sa.Float(), nullable=False),
    sa.Column('max_project_cost', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_schemes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scheme_name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=False),
    sa.Column('minimum_project_cost', sa.Float(), nullable=False),
    sa.Column('maximum_project_cost', sa.Float(), nullable=False),
    sa.Column('loan_percentage', sa.Float(), nullable=False),
    sa.Column('beneficiary_contribution', sa.Float(), nullable=False),
    sa.Column('maximum_loan', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('tenure_years', sa.Integer(), nullable=False),
    sa.Column('moratorium_months', sa.Integer(), nullable=False),
    sa.Column('repayment_frequency', sa.String(length=20), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('last_verified_date', sa.DateTime(), nullable=True),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_datasets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('training_dataset_version', sa.String(length=100), nullable=True),
    sa.Column('geographic_scope', sa.String(length=200), nullable=True),
    sa.Column('feature_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_file_location', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scoring_weight_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('demand_weight', sa.Float(), nullable=False),
    sa.Column('competition_weight', sa.Float(), nullable=False),
    sa.Column('accessibility_weight', sa.Float(), nullable=False),
    sa.Column('cost_weight', sa.Float(), nullable=False),
    sa.Column('margin_weight', sa.Float(), nullable=False),
    sa.Column('market_access_weight', sa.Float(), nullable=False),
    sa.Column('seasonality_weight', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('business_cost_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('cost_type', sa.String(length=20), nullable=False),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['business_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_revenue_assumptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('monthly_revenue_low', sa.Float(), nullable=False),
    sa.Column('monthly_revenue_high', sa.Float(), nullable=False),
    sa.Column('expected_margin_pct', sa.Float(), nullable=False),
    sa.Column('seasonality_score', sa.Float(), nullable=False),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['business_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('official_name', sa.String(length=150), nullable=True),
    sa.Column('official_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_embeddings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # embedding uses pgvector's native 'vector' type (1536-dim, matches most
    # common embedding models); ARRAY(Float) above is replaced immediately
    # below since SQLAlchemy has no built-in pgvector type without the
    # pgvector.sqlalchemy integration package.
    op.execute("ALTER TABLE document_embeddings ALTER COLUMN embedding TYPE vector(1536) USING NULL")
    op.create_index('idx_document_embeddings_chunk', 'document_embeddings', ['chunk_id'])
    op.create_table('ml_training_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dataset_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['ml_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scheme_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['loan_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_eligibility',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scheme_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('criterion', sa.String(length=200), nullable=False),
    sa.Column('required_value', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['loan_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scheme_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['loan_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('taluka_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('available_capital', sa.Float(), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('talukas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('district_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('official_name', sa.String(length=150), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('headquarters', sa.String(length=100), nullable=True),
    sa.Column('area_sq_km', sa.Float(), nullable=True),
    sa.Column('total_villages', sa.Integer(), nullable=True),
    sa.Column('rural_villages', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # spatial index auto-created by GeoAlchemy2 on table creation
    op.create_table('markets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('market_name', sa.String(length=200), nullable=False),
    sa.Column('taluka_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('market_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.Column('source_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['taluka_id'], ['talukas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # spatial index auto-created by GeoAlchemy2 on table creation
    op.create_table('villages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('district_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('taluka_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_name', sa.String(length=150), nullable=False),
    sa.Column('official_name', sa.String(length=150), nullable=True),
    sa.Column('village_code', sa.String(length=30), nullable=True),
    sa.Column('gram_panchayat', sa.String(length=150), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_type', sa.String(length=10), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('households', sa.Integer(), nullable=True),
    sa.Column('male_population', sa.Integer(), nullable=True),
    sa.Column('female_population', sa.Integer(), nullable=True),
    sa.Column('literacy_rate', sa.Float(), nullable=True),
    sa.Column('agricultural_area', sa.Float(), nullable=True),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_date', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['taluka_id'], ['talukas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # spatial index auto-created by GeoAlchemy2 on table creation
    op.create_table('agriculture_statistics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('major_crop', sa.String(length=100), nullable=True),
    sa.Column('irrigated_area', sa.Float(), nullable=True),
    sa.Column('rainfed_area', sa.Float(), nullable=True),
    sa.Column('agricultural_activity', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('source_date', sa.DateTime(), nullable=True),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_assessments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('available_capital', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('demand_score', sa.Float(), nullable=True),
    sa.Column('competition_score', sa.Float(), nullable=True),
    sa.Column('accessibility_score', sa.Float(), nullable=True),
    sa.Column('margin_score', sa.Float(), nullable=True),
    sa.Column('market_access_score', sa.Float(), nullable=True),
    sa.Column('seasonality_score', sa.Float(), nullable=True),
    sa.Column('market_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitor_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheme_match', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('swot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('dataset_version', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['business_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('owner_name', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.Column('source_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['business_categories.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # spatial index auto-created by GeoAlchemy2 on table creation
    op.create_table('gram_panchayats',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sarpanch_name', sa.String(length=150), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_statistics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_households', sa.Integer(), nullable=False),
    sa.Column('avg_household_size', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_statistics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('road_access', sa.Boolean(), nullable=True),
    sa.Column('electricity', sa.Boolean(), nullable=True),
    sa.Column('internet', sa.Boolean(), nullable=True),
    sa.Column('drinking_water', sa.Boolean(), nullable=True),
    sa.Column('bank_available', sa.Boolean(), nullable=True),
    sa.Column('atm_available', sa.Boolean(), nullable=True),
    sa.Column('primary_health_center', sa.Boolean(), nullable=True),
    sa.Column('school_available', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livestock_statistics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cattle_count', sa.Integer(), nullable=True),
    sa.Column('buffalo_count', sa.Integer(), nullable=True),
    sa.Column('goat_count', sa.Integer(), nullable=True),
    sa.Column('sheep_count', sa.Integer(), nullable=True),
    sa.Column('poultry_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('population_statistics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('village_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_prices',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('market_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('minimum_price', sa.Float(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.Column('maximum_price', sa.Float(), nullable=False),
    sa.Column('price_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['business_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_calculations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('scheme_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('available_margin', sa.Float(), nullable=False),
    sa.Column('project_cost', sa.Float(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('tenure_years', sa.Integer(), nullable=False),
    sa.Column('installment', sa.Float(), nullable=False),
    sa.Column('total_interest', sa.Float(), nullable=False),
    sa.Column('total_repayment', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['business_assessments.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['loan_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_assessments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('nearby_markets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['business_assessments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_predictions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assessment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['business_assessments.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['business_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swot_assessments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('threats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['business_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repayment_schedules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('loan_calculation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('principal_component', sa.Float(), nullable=False),
    sa.Column('interest_component', sa.Float(), nullable=False),
    sa.Column('remaining_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['loan_calculation_id'], ['loan_calculations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: 'spatial_ref_sys' is a PostGIS system table, not part of our
    # application schema - autogenerate flags it as "removed" but it must
    # never be dropped.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayment_schedules')
    op.drop_table('swot_assessments')
    op.drop_table('risk_assessments')
    op.drop_table('ml_predictions')
    op.drop_table('market_assessments')
    op.drop_table('loan_calculations')
    op.drop_table('ai_reports')
    op.drop_table('product_prices')
    op.drop_table('population_statistics')
    op.drop_table('livestock_statistics')
    op.drop_table('infrastructure_statistics')
    op.drop_table('household_statistics')
    op.drop_table('gram_panchayats')
    pass  # spatial index dropped automatically with table
    op.drop_table('businesses')
    op.drop_table('business_assessments')
    op.drop_table('agriculture_statistics')
    pass  # spatial index dropped automatically with table
    op.drop_table('villages')
    pass  # spatial index dropped automatically with table
    op.drop_table('markets')
    pass  # spatial index dropped automatically with table
    op.drop_table('talukas')
    op.drop_table('user_profiles')
    op.drop_table('scheme_versions')
    op.drop_table('scheme_eligibility')
    op.drop_table('scheme_documents')
    op.drop_table('ml_training_runs')
    op.drop_table('document_embeddings')
    op.drop_table('document_chunks')
    op.drop_table('districts')
    op.drop_table('business_revenue_assumptions')
    op.drop_table('business_cost_templates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('states')
    op.drop_table('scoring_weight_configs')
    op.drop_table('products')
    op.drop_table('ml_models')
    op.drop_table('ml_datasets')
    op.drop_table('loan_schemes')
    op.drop_table('financial_assumption_configs')
    op.drop_table('documents')
    op.drop_table('dataset_versions')
    op.drop_table('data_updates')
    op.drop_table('data_sources')
    op.drop_table('business_categories')
    # ### end Alembic commands ###
